#!/usr/bin/env python3

# Adapted from https://github.com/opsani/servo-statestore/blob/master/adjust

import os
import sys

from adjust import Adjust, AdjustError
import common
import state_store

DRIVER_NAME = "batch"
DRIVER_VERSION = "0.1"
DRIVER_DESC = "An Optune adjust driver that stores settings/parameters used in conjunction with the batch measure driver"
HAS_CANCEL=False

config_path = os.environ.get('OPTUNE_CONFIG', './config.yaml')

REQUIRED_SETTINGS_FIELDS = [ "default", "type" ]

class BatchAdjustDriver(Adjust):
    def query(self):
        return common.query_state(DRIVER_NAME, config_path)

    def adjust(self, data):
        assert ("application" in data), \
            "Invalid input: missing application key"

        config=common.parse_config(DRIVER_NAME, config_path)

        for comp_name, comp_data in config['application']['components'].items():
            agg_disk = data['application']['components'][comp_name]['settings'].get('aggregate_disk', {}).get('value')
            if agg_disk is None:
                agg_disk = comp_data['settings']['aggregate_disk']['default']
            agg_mem = data['application']['components'][comp_name]['settings'].get('aggregate_memory', {}).get('value')
            if agg_mem is None:
                agg_mem = comp_data['settings']['aggregate_memory']['default']
            inst_type = data['application']['components'][comp_name]['settings'].get('inst_type', {}).get('value')
            if inst_type is None:
                inst_type = comp_data['settings']['inst_type']['default']
            replicas = data['application']['components'][comp_name]['settings'].get('replicas', {}).get('value')
            if replicas is None:
                replicas = config['application']['components'][comp_name]['settings']['replicas']['default']

            data['application']['components'][comp_name]['settings']['instance_disk'] = {'value': int(agg_disk/replicas)}

            inst_mem = config['application']['annotations'][inst_type]['mem']
            if int(inst_mem*replicas) < agg_mem:
                raise AdjustError(f"component {comp_name}: {replicas} {inst_type} instances only have {inst_mem*replicas} GB of memory which is less than {agg_mem} GB required", 
                    status = "rejected", reason = "scheduling-failed")

        # Store application key in state
        # This may raise an exception
        state_store.set_state(data)


# initialize and run
if __name__ == "__main__":
    driver = BatchAdjustDriver(
        version = DRIVER_VERSION,
        cli_desc = DRIVER_DESC,
        supports_cancel = HAS_CANCEL,
        progress_interval = None)

    driver.run()